spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        #rup+Th6jWZE5G+NdemCvfr/nVrhAh/P3+wTaloJEdid4nKTMmD67Bfedl/etvPJLy4obNVJCcKjcYmzvrKt9Ag==
        username: root
    redis:
        port: 6379
        password: 123456
        host: 192.168.83.128
name: zhangsan123123
