eureka:
  client:
    service-url:
      defaultZone: http://192.168.83.128:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  application:
    name: clinic-zuul
server:
  port: 2103
zuul:
  prefix: /clinic
  routes:
    clinic-prescription:
      path: /prescription/**
    clinic-master-data:
      path: /masterDataAPI/**
    clinic-medicine:
      path: /medicineAPI/**
    clinic-authService: /auth/**
    clinic-order: /order/**
  add-host-header: true
#  retryable: true
  sensitive-headers:
clinic:
  jwt:
    pubKeyPath: C:\Temp\rsa\rsa.pub # 公钥地址
    cookieName: CLINIC_TOKEN
  filter:
    allowPaths:
      - /clinic/auth
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  maxAutoRetries: 1
  maxAutoRetriesNextServer: 3
  okToRetryOnAllOperations: true
  retryableStatusCodes: 500,404,502

#防止服务超时,此处设置为6秒，时长自定义
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
        timeout:
          enabled: false




