eureka:
  instance:
    hostname: eureka7003.com
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:8761/eureka/,http://eureka7002.com:8762/eureka/
server:
  port: 8763
spring:
  application:
    name: eureka-server



