eureka:
  instance:
    hostname: eureka7002.com
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:8761/eureka/,http://eureka7003.com:8763/eureka/
server:
  port: 8762
spring:
  application:
    name: eureka-server
