spring:
    application:
        name: clinic-master-data
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        #rup+Th6jWZE5G+NdemCvfr/nVrhAh/P3+wTaloJEdid4nKTMmD67Bfedl/etvPJLy4obNVJCcKjcYmzvrKt9Ag==
        username: root
